### ISSUE TITLE
xdocker Can't find AArch64 Ubuntu 18.04 Images

### ISSUE THREAD

**Issue by aarongraham9** [CAS-Atlantic/xdocker#1]
`./xdocker.sh -f /home/aaron/workspace/omropenj9/openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile aarch64 /home/aaron/`

```
TEMP: /tmp/tmp.RcN72aiQox

using a customized dockerfile: /home/aaron/workspace/omropenj9/openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile
using Arch aarch64

ERROR_ARGS: unsupported arch for custom dockerfile "ubuntu:16.04
# Download and install boot JDK AdoptOpenJDK"
	
	Usage: 
	xdocker [OPTIONS] <target architecture> <shared directory> [ <...> docker run cmd are passed through ]
	
		OPTIONS:
			-f|--file <custom dockerfile>	gives a custom dockerfile to build from. 
				This script only supports running ubuntu, but the version is pulled from your docker file

		ARGS:
			"target architecture" 		is one of x86_64%
```

**Comment by aarongraham9** [comment]
`docker --version`
```
Docker version 19.03.2, build 6a30dfc
```

**Comment by jeanlego** [comment]
could you send the dockerfile used ? 

(try putting a newline between the architecture and the comment... feeling that my sed command is the culprit, not docker search )

this is the whole input given to docker search
```
"ubuntu:18.04
# Download and install boot JDK AdoptOpenJDK"
```
not expecting that, so I probably need to fix that

**Comment by aarongraham9** [comment]
`Dockerfile` (`openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile`):

```
# Copyright (c) 2018, 2019 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception

# To use this docker file:
#   docker build -t=openj9 .
#   docker run -it openj9

FROM ubuntu:18.04

# Install required OS tools
RUN apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    software-properties-common \
  && apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    autoconf \
    ca-certificates \
    ccache \
    cmake \
    cpio \
    file \
    git \
    git-core \
    libasound2-dev \
    libcups2-dev \
    libdwarf-dev \
    libelf-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libnuma-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    libxt-dev \
    libxtst-dev \
    make \
    nasm \
    pkg-config \
    ssh \
    unzip \
    wget \
    zip \
    vim \
    build-essential \
    gdb \
    valgrind \
    libxext-dev \
    libxrender-dev \
    libxrandr-dev \
  && rm -rf /var/lib/apt/lists/*

CMD [ "/bin/bash" ]
```

**Comment by jeanlego** [comment]
... where is ```# Download and install boot JDK AdoptOpenJDK"```
comming from?

**Comment by aarongraham9** [comment]
Sorry that was supposed to be the dockerfile. But this is the one I ran instead:

```
# Copyright (c) 2018, 2019 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception

# To use this docker file:
#   docker build -t=openj9 .
#   docker run -it openj9

FROM ubuntu:16.04

# Install required OS tools
RUN apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    software-properties-common \
    python-software-properties \
  && apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    autoconf \
    ca-certificates \
    ccache \
    cmake \
    cpio \
    file \
    git \
    git-core \
    libasound2-dev \
    libcups2-dev \
    libdwarf-dev \
    libelf-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libnuma-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    libxt-dev \
    libxtst-dev \
    make \
    nasm \
    pkg-config \
    realpath \
    ssh \
    unzip \
    wget \
    zip \
    vim \
  && rm -rf /var/lib/apt/lists/*

# Add the GCC-7.3 Binary
RUN cd /usr/local \
  && wget -O gcc-7.tar.xz "https://ci.adoptopenjdk.net/userContent/gcc/gcc730+ccache.x86_64.tar.xz" \
  && tar -xJf gcc-7.tar.xz --strip-components=1 \
  && rm -rf gcc-7.tar.xz
  
# Create links for GCC to access the C library and gcc,g++
RUN ln -s /usr/lib/x86_64-linux-gnu /usr/lib64 \
  && ln -s /usr/include/x86_64-linux-gnu/* /usr/local/include \
  && ln -s /usr/local/bin/g++-7.3 /usr/bin/g++ \
  && ln -s /usr/local/bin/gcc-7.3 /usr/bin/gcc

# Download and setup freemarker.jar to /root/freemarker.jar
RUN cd /root \
  && wget https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.8.tar.gz/download -O freemarker.tgz \
  && tar -xzf freemarker.tgz freemarker-2.3.8/lib/freemarker.jar --strip=2 \
  && rm -f freemarker.tgz

# Download and install boot JDK from AdoptOpenJDK
RUN cd /root \
  && wget -O bootjdk10.tar.gz "https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk" \
  && tar -xzf bootjdk10.tar.gz \
  && rm -f bootjdk10.tar.gz \
  && mv $(ls | grep -i jdk) bootjdk10

# Set environment variable JAVA_HOME, and prepend ${JAVA_HOME}/bin to PATH
ENV JAVA_HOME="/root/bootjdk10"
ENV PATH="${JAVA_HOME}/bin:${PATH}"

WORKDIR /root
```

Both fail though.

The `# Download and install boot JDK from AdoptOpenJDK` is the second to last comment in this Dockerfile.

**Comment by aarongraham9** [comment]
@mhaque5 or @alvee-unb can you please post your output from your run of `xdocker` to compare?

**Comment by mhaque5** [comment]
Here is the error message I am getting each time.


TEMP: /tmp/tmp.AyYFz36f78

using a customized dockerfile: /home/casauser/openj9/openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile
using Arch aarch64
ERROR_ARGS: unsupported arch for custom dockerfile "ubuntu:18.04"

        Usage:
        xdocker [OPTIONS] <target architecture> <shared directory> [ <...> docker run cmd are passed through ]

                OPTIONS:
                        -f|--file <custom dockerfile>   gives a custom dockerfile to build from.
                                This script only supports running ubuntu, but the version is pulled from your docker file

                ARGS:
                        "target architecture"           is one of x86_64

________________________________

**Comment by mhaque5** [comment]
Here is the error I am getting each time:

`TEMP: /tmp/tmp.AyYFz36f78

using a customized dockerfile: /home/casauser/openj9/openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile
using Arch aarch64
ERROR_ARGS: unsupported arch for custom dockerfile "ubuntu:18.04"
	
	Usage: 
	xdocker [OPTIONS] <target architecture> <shared directory> [ <...> docker run cmd are passed through ]
	
		OPTIONS:
			-f|--file <custom dockerfile>	gives a custom dockerfile to build from. 
				This script only supports running ubuntu, but the version is pulled from your docker file

		ARGS:
			"target architecture" 		is one of x86_64`

**Comment by mhaque5** [comment]
Here is the error I am getting each time.

TEMP: /tmp/tmp.AyYFz36f78

using a customized dockerfile: /home/casauser/openj9/openj9-openjdk-jdk11/openj9/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile
using Arch aarch64
ERROR_ARGS: unsupported arch for custom dockerfile "ubuntu:18.04"
	
	Usage: 
	xdocker [OPTIONS] <target architecture> <shared directory> [ <...> docker run cmd are passed through ]
	
		OPTIONS:
			-f|--file <custom dockerfile>	gives a custom dockerfile to build from. 
				This script only supports running ubuntu, but the version is pulled from your docker file

		ARGS:
			"target architecture" 		is one of x86_64

**Comment by jeanlego** [comment]
Pr #2 should close this issue.

Works on archlinux
@aarongraham9 & @mhaque5 can you still reproduce with the fix?

**Comment by aarongraham9** [comment]
Confirmed working on a `Ubuntu 19.04` host of `x86_64` with an `AArch64` build of `OpenJ9-OpenJDK-JDK11`.

(As a side-note it seems QEMU was updated and we potentially no longer need `Arch Linux` for the `OpenJ9-OpenJDK-JDK11` builds.)

@mhaque5 and/or @alvee-unb; please confirm this works in your `Arch Linux` Environment.

Correction: `Ubuntu 19.04` NOT `Ubuntu 18.04`.

**Comment by mhaque5** [comment]
@aarongraham9 It's working perfectly. Thanks @jeanlego

**Comment by alvee-unb** [comment]
@aarongraham9 It's working for me too, thanks @jeanlego

**Comment by jeanlego** [comment]
Closing
